config/routes.rb
Rails.application.routes.draw do
  root :to => 'articles#index'
  resources :articles do
    member do
      post :notify_friend
    end
    resources :comments
  end
  resources :users
  resource :session
  get '/login' => "sessions#new", :as => "login"
  get '/loginout' => "sessions#destroy", :as => "logout"
end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlogApp</title>
    <% javascript_include_tag 'jquery-1.4.2.min', 'rails', 'application' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="header">
      <h1><%= link_to 'MyBlogApp', root_path %></h1>

      <div id="user_bar">
        <% if logged_in? %>
          <%= link_to 'New Article', new_article_path %> |
          <%= link_to 'Edit Password', edit_user_path(current_user) %> |
          <%= link_to 'Logout', logout_path %>
        <% else %>
          <%= link_to 'Login', login_path %> |
          <%= link_to 'Create user', new_user_path  %>
        <% end %>
      </div>
    </div>
    <div id="main">
      <%= content_tag :p, notice, :class => 'notice' if notice.present? %>
      <%= content_tag :p, alert, :class => 'alert' if alert.present? %>
      <%= yield %>
    </div>
    <div id="footer">
      A simple blog built from the book
      <u> Beginning Rails 3 </u>
    </div>

  </body>
</html>